server {
    listen 80;
    listen [::]:80;
    server_name *.jasperkleine.nl;

    root /usr/share/nginx/html;

    location = / {
        add_header Content-Type text/html;
        return 200 '<h1>Wildcard is working!</h1>';
    }

    location / {
        try_files /pages/404.html =404;
    }

    # Assets
    location /assets/   { root /usr/share/nginx/html; }
    location /css/      { root /usr/share/nginx/html; }
    location /js/       { root /usr/share/nginx/html; }

    # Custom 404
    error_page 404 /pages/404.html;
    location = /pages/404.html {
        internal;
    }
}