server {
    listen 80;
    listen [::]:80;
    server_name *.jasperkleine.nl;

    root /usr/share/nginx/html;

    location / {
        try_files /templates/404.html =404;
    }

    # CSS Assets
    location /static/css/      { root /usr/share/nginx/html; }
    location /static/js/       { root /usr/share/nginx/html; }

    # Custom 404
    error_page 404 /templates/404.html;
    location = /templates/404.html {
        internal;
    }
}
