services:
  jasper-nginx:
    build: .
    container_name: jasper-nginx
    restart: always
    volumes:
      - ../website/templates/:/usr/share/nginx/html/templates
      - ../website/static:/usr/share/nginx/html/static
    ports:
      - "8000:80"
    networks:
      - jasper
      - route  # Needed to communicate with the root nginx, but exclude other containers to avoid namespace conflicts

networks:
  route:
    external: true
  jasper:
    external: true
