services:
  jasper-nginx:
    build: .
    container_name: jasper-nginx
    restart: always
    volumes:
      - ../website/templates/404.html:/usr/share/nginx/html/404.html
      - ../website/static/css:/usr/share/nginx/html/static/css
    ports:
      - "8000:80"
    networks:
      - jasper
      - route  # Needed to communicate with the root nginx, but exclude other containers to avoid namespace conflicts

networks:
  route:
    external: true
  jasper:
    external: true
